CREATE ROLE dev;
GRANT usage, operate on warehouse DEV to role dev;

CREATE ROLE PROD;
GRANT ROLE DEV TO ROLE PROD;
GRANT usage, operate on warehouse PROD to role PROD;

CREATE OR REPLACE USER TRANSFORMER PASSWORD='<redacted>' default_role = PROD default_warehouse = PROD default_namespace = PROD;
GRANT ROLE PROD to user TRANSFORMER;

CREATE DATABASE RAW;

GRANT USAGE ON DATABASE RAW TO ROLE DEV;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RAW TO ROLE DEV;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE RAW TO ROLE DEV;
GRANT SELECT ON ALL TABLES IN DATABASE RAW TO ROLE DEV;
GRANT SELECT ON FUTURE TABLES IN DATABASE RAW TO ROLE DEV;
GRANT SELECT ON ALL VIEWS IN DATABASE RAW TO ROLE DEV;
GRANT SELECT ON FUTURE VIEWS IN DATABASE RAW TO ROLE DEV;


GRANT USAGE ON DATABASE RAW TO ROLE PROD;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RAW TO ROLE PROD;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE RAW TO ROLE PROD;
GRANT SELECT ON ALL TABLES IN DATABASE RAW TO ROLE PROD;
GRANT SELECT ON FUTURE TABLES IN DATABASE RAW TO ROLE PROD;
GRANT SELECT ON ALL VIEWS IN DATABASE RAW TO ROLE PROD;
GRANT SELECT ON FUTURE VIEWS IN DATABASE RAW TO ROLE PROD;


CREATE DATABASE PROD;

GRANT USAGE ON DATABASE PROD TO ROLE DEV;
GRANT USAGE ON ALL SCHEMAS IN DATABASE PROD TO ROLE DEV;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE PROD TO ROLE DEV;
GRANT SELECT ON ALL TABLES IN DATABASE PROD TO ROLE DEV;
GRANT SELECT ON FUTURE TABLES IN DATABASE PROD TO ROLE DEV;
GRANT SELECT ON ALL VIEWS IN DATABASE PROD TO ROLE DEV;
GRANT SELECT ON FUTURE VIEWS IN DATABASE PROD TO ROLE DEV;


GRANT USAGE ON DATABASE PROD TO ROLE PROD;
GRANT USAGE ON ALL SCHEMAS IN DATABASE PROD TO ROLE PROD;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE PROD TO ROLE PROD;
GRANT SELECT ON ALL TABLES IN DATABASE PROD TO ROLE PROD;
GRANT SELECT ON FUTURE TABLES IN DATABASE PROD TO ROLE PROD;
GRANT SELECT ON ALL VIEWS IN DATABASE PROD TO ROLE PROD;
GRANT SELECT ON FUTURE VIEWS IN DATABASE PROD TO ROLE PROD;


CREATE DATABASE JARED_DEV;
GRANT USAGE,CREATE SCHEMA ON DATABASE JARED_DEV TO ROLE DEV;
GRANT ALL ON ALL SCHEMAS IN DATABASE JARED_DEV TO ROLE DEV;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE JARED_DEV TO ROLE DEV;
GRANT ALL ON ALL TABLES IN DATABASE JARED_DEV TO ROLE DEV;
GRANT ALL ON FUTURE TABLES IN DATABASE JARED_DEV TO ROLE DEV;
GRANT ALL ON ALL VIEWS IN DATABASE JARED_DEV TO ROLE DEV;
GRANT ALL ON FUTURE VIEWS IN DATABASE JARED_DEV TO ROLE DEV;


CREATE DATABASE TIM_DEV;
GRANT USAGE,CREATE SCHEMA ON DATABASE TIM_DEV TO ROLE DEV;
GRANT ALL ON ALL SCHEMAS IN DATABASE TIM_DEV TO ROLE DEV;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE TIM_DEV TO ROLE DEV;
GRANT ALL ON ALL TABLES IN DATABASE TIM_DEV TO ROLE DEV;
GRANT ALL ON FUTURE TABLES IN DATABASE TIM_DEV TO ROLE DEV;
GRANT ALL ON ALL VIEWS IN DATABASE TIM_DEV TO ROLE DEV;
GRANT ALL ON FUTURE VIEWS IN DATABASE TIM_DEV TO ROLE DEV;


GRANT ROLE DEV TO USER TIMVISIVO;
GRANT ROLE DEV TO USER JAREDVISIVO;
GRANT ROLE PROD TO USER TIMVISIVO;
GRANT ROLE PROD TO USER JAREDVISIVO;


