[pytest]
env =
    CI=true
python_files = test_*.py
python_functions = test_*
testpaths = tests
addopts = --cov=visivo/server --cov-report=term-missing:skip-covered --cov-fail-under=0 --ignore=tests/sandbox