"""Reference value sets a column is matched against to call it a region.

Matching is by value, not by column name: a column called ``state`` holding
"Open"/"Closed" is a status, and one called ``region`` holding "NY"/"CA" is
geography. Lists are small on purpose: they exist to recognise the common
cases, not to validate geography.
"""

US_STATES = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "District of Columbia": "DC",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
}

NYC_BOROUGHS = ("Manhattan", "Brooklyn", "Queens", "Bronx", "Staten Island")

# (name, alpha-2, alpha-3). Curated for recognition; EWR is not a country.
COUNTRIES = (
    ("Afghanistan", "AF", "AFG"),
    ("Albania", "AL", "ALB"),
    ("Algeria", "DZ", "DZA"),
    ("Andorra", "AD", "AND"),
    ("Angola", "AO", "AGO"),
    ("Argentina", "AR", "ARG"),
    ("Armenia", "AM", "ARM"),
    ("Australia", "AU", "AUS"),
    ("Austria", "AT", "AUT"),
    ("Azerbaijan", "AZ", "AZE"),
    ("Bahamas", "BS", "BHS"),
    ("Bahrain", "BH", "BHR"),
    ("Bangladesh", "BD", "BGD"),
    ("Barbados", "BB", "BRB"),
    ("Belarus", "BY", "BLR"),
    ("Belgium", "BE", "BEL"),
    ("Belize", "BZ", "BLZ"),
    ("Benin", "BJ", "BEN"),
    ("Bhutan", "BT", "BTN"),
    ("Bolivia", "BO", "BOL"),
    ("Bosnia and Herzegovina", "BA", "BIH"),
    ("Botswana", "BW", "BWA"),
    ("Brazil", "BR", "BRA"),
    ("Brunei", "BN", "BRN"),
    ("Bulgaria", "BG", "BGR"),
    ("Burkina Faso", "BF", "BFA"),
    ("Burundi", "BI", "BDI"),
    ("Cambodia", "KH", "KHM"),
    ("Cameroon", "CM", "CMR"),
    ("Canada", "CA", "CAN"),
    ("Cape Verde", "CV", "CPV"),
    ("Central African Republic", "CF", "CAF"),
    ("Chad", "TD", "TCD"),
    ("Chile", "CL", "CHL"),
    ("China", "CN", "CHN"),
    ("Colombia", "CO", "COL"),
    ("Comoros", "KM", "COM"),
    ("Congo", "CG", "COG"),
    ("Democratic Republic of the Congo", "CD", "COD"),
    ("Costa Rica", "CR", "CRI"),
    ("Croatia", "HR", "HRV"),
    ("Cuba", "CU", "CUB"),
    ("Cyprus", "CY", "CYP"),
    ("Czech Republic", "CZ", "CZE"),
    ("Czechia", "CZ", "CZE"),
    ("Denmark", "DK", "DNK"),
    ("Djibouti", "DJ", "DJI"),
    ("Dominica", "DM", "DMA"),
    ("Dominican Republic", "DO", "DOM"),
    ("Ecuador", "EC", "ECU"),
    ("Egypt", "EG", "EGY"),
    ("El Salvador", "SV", "SLV"),
    ("Equatorial Guinea", "GQ", "GNQ"),
    ("Eritrea", "ER", "ERI"),
    ("Estonia", "EE", "EST"),
    ("Eswatini", "SZ", "SWZ"),
    ("Ethiopia", "ET", "ETH"),
    ("Fiji", "FJ", "FJI"),
    ("Finland", "FI", "FIN"),
    ("France", "FR", "FRA"),
    ("Gabon", "GA", "GAB"),
    ("Gambia", "GM", "GMB"),
    ("Georgia", "GE", "GEO"),
    ("Germany", "DE", "DEU"),
    ("Ghana", "GH", "GHA"),
    ("Greece", "GR", "GRC"),
    ("Grenada", "GD", "GRD"),
    ("Guatemala", "GT", "GTM"),
    ("Guinea", "GN", "GIN"),
    ("Guinea-Bissau", "GW", "GNB"),
    ("Guyana", "GY", "GUY"),
    ("Haiti", "HT", "HTI"),
    ("Honduras", "HN", "HND"),
    ("Hong Kong", "HK", "HKG"),
    ("Hungary", "HU", "HUN"),
    ("Iceland", "IS", "ISL"),
    ("India", "IN", "IND"),
    ("Indonesia", "ID", "IDN"),
    ("Iran", "IR", "IRN"),
    ("Iraq", "IQ", "IRQ"),
    ("Ireland", "IE", "IRL"),
    ("Israel", "IL", "ISR"),
    ("Italy", "IT", "ITA"),
    ("Ivory Coast", "CI", "CIV"),
    ("Jamaica", "JM", "JAM"),
    ("Japan", "JP", "JPN"),
    ("Jordan", "JO", "JOR"),
    ("Kazakhstan", "KZ", "KAZ"),
    ("Kenya", "KE", "KEN"),
    ("Kiribati", "KI", "KIR"),
    ("Kuwait", "KW", "KWT"),
    ("Kyrgyzstan", "KG", "KGZ"),
    ("Laos", "LA", "LAO"),
    ("Latvia", "LV", "LVA"),
    ("Lebanon", "LB", "LBN"),
    ("Lesotho", "LS", "LSO"),
    ("Liberia", "LR", "LBR"),
    ("Libya", "LY", "LBY"),
    ("Liechtenstein", "LI", "LIE"),
    ("Lithuania", "LT", "LTU"),
    ("Luxembourg", "LU", "LUX"),
    ("Madagascar", "MG", "MDG"),
    ("Malawi", "MW", "MWI"),
    ("Malaysia", "MY", "MYS"),
    ("Maldives", "MV", "MDV"),
    ("Mali", "ML", "MLI"),
    ("Malta", "MT", "MLT"),
    ("Marshall Islands", "MH", "MHL"),
    ("Mauritania", "MR", "MRT"),
    ("Mauritius", "MU", "MUS"),
    ("Mexico", "MX", "MEX"),
    ("Micronesia", "FM", "FSM"),
    ("Moldova", "MD", "MDA"),
    ("Monaco", "MC", "MCO"),
    ("Mongolia", "MN", "MNG"),
    ("Montenegro", "ME", "MNE"),
    ("Morocco", "MA", "MAR"),
    ("Mozambique", "MZ", "MOZ"),
    ("Myanmar", "MM", "MMR"),
    ("Namibia", "NA", "NAM"),
    ("Nauru", "NR", "NRU"),
    ("Nepal", "NP", "NPL"),
    ("Netherlands", "NL", "NLD"),
    ("New Zealand", "NZ", "NZL"),
    ("Nicaragua", "NI", "NIC"),
    ("Niger", "NE", "NER"),
    ("Nigeria", "NG", "NGA"),
    ("North Korea", "KP", "PRK"),
    ("North Macedonia", "MK", "MKD"),
    ("Norway", "NO", "NOR"),
    ("Oman", "OM", "OMN"),
    ("Pakistan", "PK", "PAK"),
    ("Palau", "PW", "PLW"),
    ("Palestine", "PS", "PSE"),
    ("Panama", "PA", "PAN"),
    ("Papua New Guinea", "PG", "PNG"),
    ("Paraguay", "PY", "PRY"),
    ("Peru", "PE", "PER"),
    ("Philippines", "PH", "PHL"),
    ("Poland", "PL", "POL"),
    ("Portugal", "PT", "PRT"),
    ("Puerto Rico", "PR", "PRI"),
    ("Qatar", "QA", "QAT"),
    ("Romania", "RO", "ROU"),
    ("Russia", "RU", "RUS"),
    ("Rwanda", "RW", "RWA"),
    ("Saint Kitts and Nevis", "KN", "KNA"),
    ("Saint Lucia", "LC", "LCA"),
    ("Saint Vincent and the Grenadines", "VC", "VCT"),
    ("Samoa", "WS", "WSM"),
    ("San Marino", "SM", "SMR"),
    ("Sao Tome and Principe", "ST", "STP"),
    ("Saudi Arabia", "SA", "SAU"),
    ("Senegal", "SN", "SEN"),
    ("Serbia", "RS", "SRB"),
    ("Seychelles", "SC", "SYC"),
    ("Sierra Leone", "SL", "SLE"),
    ("Singapore", "SG", "SGP"),
    ("Slovakia", "SK", "SVK"),
    ("Slovenia", "SI", "SVN"),
    ("Solomon Islands", "SB", "SLB"),
    ("Somalia", "SO", "SOM"),
    ("South Africa", "ZA", "ZAF"),
    ("South Korea", "KR", "KOR"),
    ("South Sudan", "SS", "SSD"),
    ("Spain", "ES", "ESP"),
    ("Sri Lanka", "LK", "LKA"),
    ("Sudan", "SD", "SDN"),
    ("Suriname", "SR", "SUR"),
    ("Sweden", "SE", "SWE"),
    ("Switzerland", "CH", "CHE"),
    ("Syria", "SY", "SYR"),
    ("Taiwan", "TW", "TWN"),
    ("Tajikistan", "TJ", "TJK"),
    ("Tanzania", "TZ", "TZA"),
    ("Thailand", "TH", "THA"),
    ("Timor-Leste", "TL", "TLS"),
    ("Togo", "TG", "TGO"),
    ("Tonga", "TO", "TON"),
    ("Trinidad and Tobago", "TT", "TTO"),
    ("Tunisia", "TN", "TUN"),
    ("Turkey", "TR", "TUR"),
    ("Turkmenistan", "TM", "TKM"),
    ("Tuvalu", "TV", "TUV"),
    ("Uganda", "UG", "UGA"),
    ("Ukraine", "UA", "UKR"),
    ("United Arab Emirates", "AE", "ARE"),
    ("United Kingdom", "GB", "GBR"),
    ("United States", "US", "USA"),
    ("United States of America", "US", "USA"),
    ("Uruguay", "UY", "URY"),
    ("Uzbekistan", "UZ", "UZB"),
    ("Vanuatu", "VU", "VUT"),
    ("Vatican City", "VA", "VAT"),
    ("Venezuela", "VE", "VEN"),
    ("Vietnam", "VN", "VNM"),
    ("Yemen", "YE", "YEM"),
    ("Zambia", "ZM", "ZMB"),
    ("Zimbabwe", "ZW", "ZWE"),
)

# geo_kind -> the set of accepted (case-folded) values.
GEO_VALUE_SETS = {
    "us_state": {n.casefold() for n in US_STATES} | {a.casefold() for a in US_STATES.values()},
    "country_name": {c[0].casefold() for c in COUNTRIES},
    "iso2": {c[1].casefold() for c in COUNTRIES},
    "iso3": {c[2].casefold() for c in COUNTRIES},
    "custom": {b.casefold() for b in NYC_BOROUGHS},
}

# Two-letter US state codes collide with ISO alpha-2 (CA, DE, GA, IN, ...),
# so a tie is broken in this order: a full name is unambiguous, a 3-letter code
# is a country, and a 2-letter code is read as a state before a country.
GEO_KIND_PRIORITY = ("us_state", "country_name", "iso3", "iso2", "custom")


def geo_kind_for(values, min_share=0.9):
    """The ``geo_kind`` whose set covers at least ``min_share`` of ``values``,
    or ``None``. ``values`` are the distinct values seen (not weighted)."""
    folded = [str(v).strip().casefold() for v in values if v is not None and str(v).strip()]
    if len(folded) < 2:
        return None
    for kind in GEO_KIND_PRIORITY:
        accepted = GEO_VALUE_SETS[kind]
        share = sum(1 for v in folded if v in accepted) / len(folded)
        if share >= min_share:
            return kind
    return None
