/**
 * Project Schema Registry (VIS-991)
 *
 * Loader registry for the bundled Visivo project schema — the 103-entry `$defs`
 * graph generated from the Pydantic models. This is the schema-form engine's
 * source of object shapes (Dimension, Metric, Relation, Model, …), parallel to
 * `schemas.js` which serves the per-trace Plotly property schemas.
 *
 * The bundled JSON snapshot lives at `./visivo_project_schema.json`. It is a
 * COMMITTED copy of `visivo/src/visivo_project_schema.json`, regenerated by:
 *
 *     python -m visivo.generate_project_schema_json
 *
 * and re-copied into this directory. `copy-schemas` (the `cp ../visivo/schema/
 * *.schema.json` build step) only touches `*.schema.json` files, so this
 * snapshot is never clobbered by a build — it must be refreshed by hand when
 * the project models change.
 *
 * `getObjectSchema(type)` returns the `$defs/<Type>` slice for an object type
 * WITH the full `$defs` namespace re-attached, so the SchemaEditor's
 * `resolveRef`/`getStaticSchema` helpers can resolve `#/$defs/...` references
 * against the complete graph.
 */

// Cache for the loaded root schema (the whole 103-entry $defs document).
let rootSchemaCache = null;

// In-flight load promise so concurrent callers share a single dynamic import.
let loadingPromise = null;

// Per-type cache for the assembled `$defs`-attached object schema slices.
const objectSchemaCache = {};

/**
 * Map of lowercase object types (as used across the workspace / objectTypeConfigs)
 * to the PascalCase `$defs` entry name in the project schema.
 */
export const OBJECT_TYPE_TO_DEF = {
  dimension: 'Dimension',
  metric: 'Metric',
  relation: 'Relation',
  model: 'Model',
  source: 'Source',
  insight: 'Insight',
  chart: 'Chart',
  table: 'Table',
  markdown: 'Markdown',
  input: 'Input',
  dashboard: 'Dashboard',
  csvscriptmodel: 'CsvScriptModel',
  localmergemodel: 'LocalMergeModel',
  defaults: 'Defaults',
  // Dashboard structure children — not Library object types, but the
  // validation-as-save gate (VIS-993) validates Item/Row mutations against
  // their defs so structure configs are born backend-valid.
  item: 'Item',
  row: 'Row',
};

/**
 * Resolve an object type (lowercase / camelCase / PascalCase) to its `$defs`
 * entry name. Returns null when the type has no known mapping.
 *
 * @param {string} type - The object type (e.g. 'dimension', 'csvScriptModel')
 * @returns {string|null} The PascalCase def name or null
 */
export function getDefNameForType(type) {
  if (!type || typeof type !== 'string') return null;
  const key = type.toLowerCase();
  return OBJECT_TYPE_TO_DEF[key] || null;
}

/**
 * Lazily dynamic-import the bundled project schema and cache it.
 * @returns {Promise<object>} The full project schema (with `$defs`)
 */
async function loadRootSchema() {
  if (rootSchemaCache) return rootSchemaCache;
  if (loadingPromise) return loadingPromise;

  loadingPromise = (async () => {
    try {
      const mod = await import('./visivo_project_schema.json');
      const schema = mod.default || mod;
      rootSchemaCache = schema;
      loadingPromise = null;
      return schema;
    } catch (error) {
      loadingPromise = null;
      throw error;
    }
  })();

  return loadingPromise;
}

/**
 * Preload the project schema (e.g. when a workspace pane mounts) so a later
 * `getObjectSchema` call resolves without an async hop.
 * @returns {Promise<void>}
 */
export async function preloadProjectSchema() {
  await loadRootSchema();
}

/**
 * Drop every module-level cache (VIS-1025). The caches carry no project
 * identity, so the store layer calls this when the active `project.id`
 * CHANGES (commonStore) — the next load re-binds against the new project.
 * validateAgainstSchema keeps its own compiled-validator cache on top; its
 * `clearValidationCache` is cleared alongside this at the same seam.
 */
export function resetProjectSchemaCache() {
  rootSchemaCache = null;
  loadingPromise = null;
  Object.keys(objectSchemaCache).forEach(key => {
    delete objectSchemaCache[key];
  });
}

/**
 * Whether the project schema has finished loading (and is cached).
 * @returns {boolean}
 */
export function isObjectSchemaLoaded() {
  return rootSchemaCache !== null;
}

/**
 * Get the schema slice for a Visivo object type, with the full `$defs`
 * namespace re-attached so `#/$defs/...` references resolve.
 *
 * @param {string} type - The object type (e.g. 'dimension', 'metric')
 * @returns {Promise<object|null>} The `$defs/<Type>` slice (+ `$defs`), or null
 */
export async function getObjectSchema(type) {
  const defName = getDefNameForType(type);
  if (!defName) return null;

  if (objectSchemaCache[defName]) return objectSchemaCache[defName];

  let root;
  try {
    root = await loadRootSchema();
  } catch (error) {
    console.error('Failed to load project schema:', error);
    return null;
  }

  const defs = root?.$defs || {};
  const slice = defs[defName];
  if (!slice) return null;

  // Re-attach the full $defs graph so resolveRef/getStaticSchema can resolve
  // every `#/$defs/...` reference the slice (or its descendants) may use.
  const assembled = { ...slice, $defs: defs };
  objectSchemaCache[defName] = assembled;
  return assembled;
}

/**
 * Synchronous accessor — returns the assembled object schema slice only if the
 * root schema is already cached, otherwise null. Useful for render paths that
 * have already preloaded.
 *
 * @param {string} type - The object type
 * @returns {object|null}
 */
export function getObjectSchemaSync(type) {
  const defName = getDefNameForType(type);
  if (!defName) return null;
  if (objectSchemaCache[defName]) return objectSchemaCache[defName];
  if (!rootSchemaCache) return null;

  const defs = rootSchemaCache.$defs || {};
  const slice = defs[defName];
  if (!slice) return null;
  const assembled = { ...slice, $defs: defs };
  objectSchemaCache[defName] = assembled;
  return assembled;
}
