import { getUrl } from '../contexts/URLContext';

/**
 * Fetch the URL for input options JSON file
 *
 * @param {string} projectId - Project ID (unused in local mode, but kept for API compatibility)
 * @param {string} inputHash - MD5 hash of the input name (generated by backend)
 * @returns {Promise<string>} - URL to the JSON file containing input options
 */
export const fetchInputOptions = async (projectId, inputHash) => {
  try {
    // In dist mode: /data/inputs/{hash}.json
    // In server mode: /data/inputs/{hash}.json
    const url = getUrl('inputData', { hash: inputHash });
    console.debug(`Input options URL for ${inputHash}: ${url}`);
    return url;
  } catch (error) {
    console.error(`Failed to fetch input options URL for ${inputHash}:`, error);
    throw error;
  }
};

/**
 * Input data structure from JSON file
 * @typedef {Object} InputData
 * @property {string} input_name - Name of the input
 * @property {string} input_hash - MD5 hash of the input name
 * @property {'single-select'|'multi-select'} type - Input type
 * @property {'options'|'range'} structure - Data structure type
 * @property {Object} results - Results data
 * @property {string[]|null} results.options - Array of options (for options structure)
 * @property {Object|null} results.range - Range configuration (for range structure)
 * @property {number} results.range.start - Start value
 * @property {number} results.range.end - End value
 * @property {number} results.range.step - Step value
 * @property {Object|null} results.display - Display configuration
 */

/**
 * Load input data from JSON file URL
 *
 * This function fetches the JSON file and returns the parsed input data structure.
 * The JSON file contains the input configuration including options or range data.
 *
 * @param {string} url - URL to the JSON file
 * @returns {Promise<InputData>} - Parsed input data
 */
export const loadInputData = async url => {
  try {
    console.debug(`Loading input data from ${url}`);

    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`Failed to fetch input JSON: ${response.status} ${response.statusText}`);
    }

    const data = await response.json();
    console.debug(`Loaded input data: ${data.input_name}, type: ${data.type}`);
    return data;
  } catch (error) {
    console.error(`Failed to load input data from ${url}:`, error);
    throw new Error(`Failed to load input data: ${error.message}`);
  }
};

/**
 * Load input options from JSON file (legacy API for backwards compatibility)
 *
 * @deprecated Use loadInputData instead for full input structure
 * @param {any} db - DuckDB instance (no longer used, kept for API compatibility)
 * @param {string} url - URL to the JSON file
 * @returns {Promise<string[]>} - Array of option values (as strings)
 */
export const loadInputOptions = async (db, url) => {
  try {
    const data = await loadInputData(url);

    // Extract options based on structure
    if (data.structure === 'options' && data.results?.options) {
      return data.results.options.map(String);
    } else if (data.structure === 'range' && data.results?.range) {
      // Generate options from range
      const { start, end, step } = data.results.range;
      const options = [];
      for (let val = start; val <= end; val += step) {
        options.push(String(val));
      }
      return options;
    }

    console.warn(`Unknown input structure: ${data.structure}`);
    return [];
  } catch (error) {
    console.error(`Failed to load input options from ${url}:`, error);
    throw new Error(`Failed to load input options: ${error.message}`);
  }
};
