import { getUrl } from '../contexts/URLContext';

/**
 * Fetch the URL for input options parquet file
 *
 * @param {string} projectId - Project ID (unused in local mode, but kept for API compatibility)
 * @param {string} inputHash - MD5 hash of the input name (generated by backend)
 * @returns {Promise<string>} - URL to the parquet file containing input options
 */
export const fetchInputOptions = async (projectId, inputHash) => {
  try {
    // In dist mode: /data/inputs/{hash}.parquet
    // In server mode: /api/inputs/{hash}.parquet (would need backend endpoint)
    // For now, construct URL directly since inputs are static files
    const url = getUrl('inputData', { hash: inputHash });
    console.debug(`Input options URL for ${inputHash}: ${url}`);
    return url;
  } catch (error) {
    console.error(`Failed to fetch input options URL for ${inputHash}:`, error);
    throw error;
  }
};

/**
 * Load input options from parquet file URL using DuckDB
 *
 * This function queries the parquet file and returns the 'option' column as an array of strings.
 * The parquet file is expected to have a single column named 'option'.
 *
 * @param {import("@duckdb/duckdb-wasm").AsyncDuckDB} db - DuckDB instance
 * @param {string} url - URL to the parquet file
 * @returns {Promise<string[]>} - Array of option values (as strings)
 */
export const loadInputOptions = async (db, url) => {
  try {
    console.debug(`Loading input options from ${url}`);

    // Query the parquet file directly - DuckDB can read from HTTP URLs
    const conn = await db.connect();
    try {
      const result = await conn.query(`SELECT option FROM read_parquet('${url}')`);

      // Extract the 'option' column
      const optionColumn = result.getChild('option');
      if (!optionColumn) {
        throw new Error('Parquet file does not contain "option" column');
      }

      // Convert to array of strings
      const options = [];
      for (let i = 0; i < optionColumn.length; i++) {
        const value = optionColumn.get(i);
        options.push(String(value));
      }

      console.debug(`Loaded ${options.length} options from ${url}`);
      return options;
    } finally {
      await conn.close();
    }
  } catch (error) {
    console.error(`Failed to load input options from ${url}:`, error);
    throw new Error(`Failed to load input options: ${error.message}`);
  }
};
