import { getUrl } from '../contexts/URLContext';

/**
 * Fetch the URL for input options JSON file
 *
 * @param {string} projectId - Project ID (unused in local mode, but kept for API compatibility)
 * @param {string} inputHash - MD5 hash of the input name (generated by backend)
 * @returns {Promise<string>} - URL to the JSON file containing input options
 */
export const fetchInputOptions = async (projectId, inputHash) => {
  try {
    // In dist mode: /data/inputs/{hash}.json
    // In server mode: /data/inputs/{hash}.json
    const url = getUrl('inputData', { hash: inputHash });
    console.debug(`Input options URL for ${inputHash}: ${url}`);
    return url;
  } catch (error) {
    console.error(`Failed to fetch input options URL for ${inputHash}:`, error);
    throw error;
  }
};

/**
 * Input data structure from JSON file
 * @typedef {Object} InputData
 * @property {string} input_name - Name of the input
 * @property {string} input_hash - MD5 hash of the input name
 * @property {'single-select'|'multi-select'} type - Input type
 * @property {'options'|'range'} structure - Data structure type
 * @property {Object} results - Results data
 * @property {string[]|null} results.options - Array of options (for options structure)
 * @property {Object|null} results.range - Range configuration (for range structure)
 * @property {number} results.range.start - Start value
 * @property {number} results.range.end - End value
 * @property {number} results.range.step - Step value
 * @property {Object|null} results.display - Display configuration
 */

/**
 * Load input data from JSON file URL
 *
 * This function fetches the JSON file and returns the parsed input data structure.
 * The JSON file contains the input configuration including options or range data.
 *
 * @param {string} url - URL to the JSON file
 * @returns {Promise<InputData>} - Parsed input data
 */
export const loadInputData = async url => {
  try {
    console.debug(`Loading input data from ${url}`);

    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`Failed to fetch input JSON: ${response.status} ${response.statusText}`);
    }

    const data = await response.json();
    console.debug(`Loaded input data: ${data.input_name}, type: ${data.type}`);
    return data;
  } catch (error) {
    console.error(`Failed to load input data from ${url}:`, error);
    throw new Error(`Failed to load input data: ${error.message}`);
  }
};

