import { tableColumnsWithDot } from './Table';

// Generated by CodiumAI

describe('tableColumnsWithDot', () => {

  // returns columns with accessorKey when table.columns is defined
  it('should return columns with accessorKey when table.columns is defined', () => {
    const table = {
      columns: [
        { key: 'name', header: 'Name' },
        { key: 'age', header: 'Age' }
      ]
    };
    const result = tableColumnsWithDot(table, null);
    expect(result).toEqual([
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'age', header: 'Age' }
    ]);
  });

  it('should return columns with accessorKey when table.columns without header is defined', () => {
    const table = {
      columns: [
        { key: 'name' },
        { key: 'age' }
      ]
    };
    const result = tableColumnsWithDot(table, null);
    expect(result).toEqual([
      { accessorKey: 'name', header: 'name' },
      { accessorKey: 'age', header: 'age' }
    ]);
  });

  it('should handle empty table.columns array correctly', () => {
    const table = {
      columns: []
    };
    const result = tableColumnsWithDot(table, null);
    expect(result).toEqual([]);
  });
});
