/* eslint-disable no-template-curly-in-string -- assertions use literal Visivo `${ref(...)}` strings */
import React from 'react';
import { render, screen, fireEvent, cleanup, act } from '@testing-library/react';
import selectEvent from 'react-select-event';
import { DndContext } from '@dnd-kit/core';
import ItemEditForm, {
  getItemLeafRef,
  isContainerItem,
  ALLOWED_LEAF_TYPES,
} from './ItemEditForm';
import RowEditForm from './RowEditForm';
import useStore from '../../../stores/store';
import { setWorkspaceTelemetryListener } from '../workspace/telemetry';

const leafItem = { width: 2, chart: 'ref(rev_chart)', table: '', markdown: '', selector: '', input: '' };
const emptyItem = { width: 1, chart: '', table: '', markdown: '', selector: '', input: '' };
const containerItem = {
  width: 1,
  rows: [
    { height: 'small', items: [{ width: 1, chart: 'ref(small_a)' }] },
    { height: 'small', items: [{ width: 1, chart: 'ref(small_b)' }] },
  ],
};

const renderItem = (props = {}) =>
  render(
    <DndContext>
      <ItemEditForm
        item={leafItem}
        itemId="row-0-item-0"
        itemIndex={0}
        onChange={() => {}}
        onRemove={() => {}}
        onSelectRef={() => {}}
        RowComponent={RowEditForm}
        {...props}
      />
    </DndContext>
  );

describe('helpers', () => {
  test('getItemLeafRef resolves chart/table refs and null for empty/container', () => {
    expect(getItemLeafRef({ chart: 'ref(c1)' })).toEqual({ type: 'chart', name: 'c1', inline: false });
    expect(getItemLeafRef({ table: 'ref(t1)' })).toEqual({ type: 'table', name: 't1', inline: false });
    expect(getItemLeafRef(emptyItem)).toBeNull();
    expect(getItemLeafRef(containerItem)).toBeNull();
    expect(getItemLeafRef(null)).toBeNull();
  });
  test('getItemLeafRef resolves a NAMED compiled object to its name', () => {
    expect(getItemLeafRef({ chart: { name: 'c1', path: 'project.charts[0]' } })).toEqual({
      type: 'chart',
      name: 'c1',
      inline: false,
    });
  });
  test('getItemLeafRef flags an INLINE/unnamed object (no name) instead of using its path', () => {
    // An inline markdown defined in place has only an autogenerated path, no name.
    const inlineMarkdown = { markdown: { path: 'project.dashboards[0].rows[0].items[0].markdown' } };
    expect(getItemLeafRef(inlineMarkdown)).toEqual({ type: 'markdown', name: null, inline: true });
  });
  test('isContainerItem true only when rows is an array', () => {
    expect(isContainerItem(containerItem)).toBe(true);
    expect(isContainerItem(leafItem)).toBe(false);
    expect(isContainerItem(null)).toBe(false);
  });
  test('ALLOWED_LEAF_TYPES is the 4 leaf types', () => {
    expect(ALLOWED_LEAF_TYPES).toEqual(['chart', 'table', 'markdown', 'input']);
  });
});

describe('ItemEditForm — leaf variant (standalone)', () => {
  test('renders width input, mode toggle, and a leaf RefDropZone', () => {
    renderItem();
    expect(screen.getByLabelText('Item 1 width')).toHaveValue(2);
    expect(screen.getByTestId('item-row-0-item-0-mode-leaf')).toHaveAttribute('aria-checked', 'true');
    expect(screen.getByTestId('item-row-0-item-0-mode-container')).toHaveAttribute('aria-checked', 'false');
    // Default leaf id is item-<itemId>-leaf.
    expect(screen.getByTestId('ref-dropzone-item-row-0-item-0-leaf')).toBeInTheDocument();
  });

  test('a filled leaf renders the EmbeddedPill for the ref', () => {
    renderItem();
    const slot = screen.getByTestId('ref-dropzone-item-row-0-item-0-leaf');
    expect(slot).toHaveAttribute('data-filled', 'true');
    expect(screen.getByText('rev_chart')).toBeInTheDocument();
  });

  test('an empty leaf renders the empty drop-zone visual', () => {
    renderItem({ item: emptyItem });
    const slot = screen.getByTestId('ref-dropzone-item-row-0-item-0-leaf');
    expect(slot).toHaveAttribute('data-filled', 'false');
  });

  test('leafDropZoneId override is honored (bundled legacy id)', () => {
    renderItem({ leafDropZoneId: 'row-0-item-0' });
    expect(screen.getByTestId('ref-dropzone-row-0-item-0')).toBeInTheDocument();
  });

  test('width change reports a born-valid nextItem (integer width, no blank leaf keys)', () => {
    const onChange = jest.fn();
    renderItem({ onChange });
    fireEvent.change(screen.getByLabelText('Item 1 width'), { target: { value: '4' } });
    // VIS-993: the emitted item is backend-valid as-is — the width is an
    // INTEGER (never the raw input string) and the legacy blank leaf keys +
    // the non-model `selector` scaffold are gone.
    expect(onChange).toHaveBeenCalledWith({ width: 4, chart: 'ref(rev_chart)' });
  });

  test('removing the pill clears the leaf ref to a bare empty slot', () => {
    const onChange = jest.fn();
    renderItem({ onChange });
    fireEvent.click(screen.getByTestId('pill-remove'));
    const next = onChange.mock.calls[0][0];
    expect(getItemLeafRef(next)).toBeNull();
    expect(next.rows).toBeUndefined();
    // VIS-993: cleared means the keys are GONE — not reset to empty strings.
    expect(next).toEqual({ width: 2 });
  });

  test('clicking the pill calls onSelectRef with the referenced object', () => {
    const onSelectRef = jest.fn();
    renderItem({ onSelectRef });
    fireEvent.click(screen.getByText('rev_chart'));
    expect(onSelectRef).toHaveBeenCalledWith({ type: 'chart', name: 'rev_chart' });
  });

  test('onRemove fires from the remove-item button', () => {
    const onRemove = jest.fn();
    renderItem({ onRemove });
    fireEvent.click(screen.getByLabelText('Remove item 1'));
    expect(onRemove).toHaveBeenCalled();
  });
});

describe('ItemEditForm — mutual exclusion (validate_unique_item_types)', () => {
  test('dropping a second-type ref clears the existing leaf first (only one type set)', () => {
    // Exercise the exact path the shell drop (G-1) will use: RefDropZone's
    // `onChange({ type, name })`. Start from a *chart* leaf and write a *table*
    // ref; ItemEditForm must reset all leaf fields so only `table` survives.
    let capturedOnChange;
    jest.isolateModules(() => {
      jest.doMock('./RefDropZone', () => ({
        __esModule: true,
        default: ({ onChange }) => {
          capturedOnChange = onChange;
          return <div data-testid="mock-refdropzone" />;
        },
      }));
      const Item = require('./ItemEditForm').default;
      const onChange = jest.fn();
      render(
        <DndContext>
          <Item
            item={leafItem}
            itemId="row-0-item-0"
            itemIndex={0}
            onChange={onChange}
            RowComponent={RowEditForm}
          />
        </DndContext>
      );
      capturedOnChange({ type: 'table', name: 'sales_table' });
      const next = onChange.mock.calls[0][0];
      // VIS-993: the item is born valid — exactly ONE leaf key remains (the
      // new table ref, in the serialized ${ref()} form); the competing chart
      // key and the legacy empty-string/selector scaffold keys are GONE.
      expect(next).toEqual({ width: 2, table: '${ref(sales_table)}' });
      ['chart', 'markdown', 'input', 'selector', 'rows'].forEach(k =>
        expect(k in next).toBe(false)
      );
    });
  });

  test('switching to container drops the leaf ref; switching back drops rows', () => {
    const onChange = jest.fn();
    renderItem({ onChange, item: leafItem });
    fireEvent.click(screen.getByTestId('item-row-0-item-0-mode-container'));
    const asContainer = onChange.mock.calls[0][0];
    expect(Array.isArray(asContainer.rows)).toBe(true);
    expect(getItemLeafRef(asContainer)).toBeNull();
    // VIS-993: the seeded container is born valid — one nested row holding one
    // bare empty slot (never an empty items array / empty-string leaves).
    expect(asContainer).toEqual({
      width: 2,
      rows: [{ height: 'medium', items: [{ width: 1 }] }],
    });

    cleanup();
    onChange.mockClear();
    renderItem({ onChange, item: containerItem });
    fireEvent.click(screen.getByTestId('item-row-0-item-0-mode-leaf'));
    const asLeaf = onChange.mock.calls[0][0];
    expect(asLeaf.rows).toBeUndefined();
    expect(getItemLeafRef(asLeaf)).toBeNull();
    expect(asLeaf).toEqual({ width: 1 });
  });
});

describe('ItemEditForm — container variant (Item.rows)', () => {
  const renderContainer = (props = {}) =>
    render(
      <DndContext>
        <ItemEditForm
          item={containerItem}
          itemId="row-0-item-0"
          itemIndex={0}
          onChange={() => {}}
          onSelectRef={() => {}}
          RowComponent={RowEditForm}
          {...props}
        />
      </DndContext>
    );

  test('renders nested rows via RowComponent and marks container mode active', () => {
    renderContainer();
    expect(screen.getByTestId('item-row-0-item-0-mode-container')).toHaveAttribute('aria-checked', 'true');
    expect(screen.getByTestId('item-row-0-item-0-rows')).toBeInTheDocument();
    // Two nested rows rendered through RowEditForm.
    expect(screen.getByTestId('row-edit-form-row-0-item-0-0')).toBeInTheDocument();
    expect(screen.getByTestId('row-edit-form-row-0-item-0-1')).toBeInTheDocument();
    expect(screen.getByText('small_a')).toBeInTheDocument();
    expect(screen.getByText('small_b')).toBeInTheDocument();
  });

  test('Add Nested Row appends a born-valid sub-row (one bare empty slot)', () => {
    const onChange = jest.fn();
    renderContainer({ onChange });
    fireEvent.click(screen.getByText('+ Add Nested Row'));
    const next = onChange.mock.calls[0][0];
    expect(next.rows).toHaveLength(3);
    // VIS-993: the new sub-row holds ONE empty slot with no scaffold keys.
    expect(next.rows[2]).toEqual({ height: 'medium', items: [{ width: 1 }] });
  });

  test('removing a nested row drops it from rows', () => {
    const onChange = jest.fn();
    renderContainer({ onChange });
    fireEvent.click(screen.getByLabelText('Remove row 1'));
    const next = onChange.mock.calls[0][0];
    expect(next.rows).toHaveLength(1);
    expect(next.rows[0].items[0].chart).toBe('ref(small_b)');
  });

  test('reorder: move row 1 down swaps the two nested rows', () => {
    const onChange = jest.fn();
    renderContainer({ onChange });
    fireEvent.click(screen.getByLabelText('Move nested row 1 down'));
    const next = onChange.mock.calls[0][0];
    expect(next.rows[0].items[0].chart).toBe('ref(small_b)');
    expect(next.rows[1].items[0].chart).toBe('ref(small_a)');
  });

  test('move up is disabled for the first row, move down for the last', () => {
    renderContainer();
    expect(screen.getByLabelText('Move nested row 1 up')).toBeDisabled();
    expect(screen.getByLabelText('Move nested row 2 down')).toBeDisabled();
  });

  test('reorder: move row 2 up swaps the two nested rows', () => {
    const onChange = jest.fn();
    renderContainer({ onChange });
    fireEvent.click(screen.getByLabelText('Move nested row 2 up'));
    const next = onChange.mock.calls[0][0];
    expect(next.rows[0].items[0].chart).toBe('ref(small_b)');
    expect(next.rows[1].items[0].chart).toBe('ref(small_a)');
  });

  test('Add Item inside a nested sub-row appends an empty item to that row only', () => {
    const onChange = jest.fn();
    renderContainer({ onChange });
    fireEvent.click(screen.getAllByRole('button', { name: /Add Item/ })[0]);
    const next = onChange.mock.calls[0][0];
    expect(next.rows[0].items).toHaveLength(2);
    expect(getItemLeafRef(next.rows[0].items[1])).toBeNull();
    // VIS-993: the appended slot is a bare { width } — no scaffold keys.
    expect(next.rows[0].items[1]).toEqual({ width: 1 });
    expect(next.rows[1].items).toHaveLength(1);
  });

  test('removing a nested sub-row item drops it from that sub-row', () => {
    const onChange = jest.fn();
    renderContainer({ onChange });
    // The container item itself has no onRemove here, so the only
    // "Remove item 1" buttons belong to the nested rows' items.
    fireEvent.click(screen.getAllByLabelText('Remove item 1')[0]);
    const next = onChange.mock.calls[0][0];
    expect(next.rows[0].items).toHaveLength(0);
    expect(next.rows[1].items[0].chart).toBe('ref(small_b)');
  });

  test('changing a nested item width routes into the container item update', () => {
    const onChange = jest.fn();
    renderContainer({ onChange });
    // [0] is the container item's own width input; [1] is nested row 1's item.
    fireEvent.change(screen.getAllByLabelText('Item 1 width')[1], { target: { value: '4' } });
    const next = onChange.mock.calls[0][0];
    // VIS-993: the width is written as an INTEGER (born valid), leaf preserved.
    expect(next.rows[0].items[0]).toEqual({ width: 4, chart: 'ref(small_a)' });
    expect(next.rows[1].items[0].width).toBe(1);
  });

  test('clearing a nested item ref removes its leaf fields (other rows untouched)', () => {
    const onChange = jest.fn();
    renderContainer({ onChange });
    // Remove the pill on the first nested row's item (small_a).
    fireEvent.click(screen.getAllByTestId('pill-remove')[0]);
    const next = onChange.mock.calls[0][0];
    expect(getItemLeafRef(next.rows[0].items[0])).toBeNull();
    // VIS-993: cleared means the key is GONE — never an empty string.
    expect(next.rows[0].items[0]).toEqual({ width: 1 });
    expect(next.rows[1].items[0].chart).toBe('ref(small_b)');
  });

  test('editing a nested row height reports the updated container item', async () => {
    const onChange = jest.fn();
    renderContainer({ onChange });
    // Row height is the brand <Select>; pick "large" from its portaled menu.
    await selectEvent.select(screen.getByLabelText('Row 1 height'), 'large', {
      container: document.body,
    });
    const next = onChange.mock.calls[0][0];
    expect(next.rows[0].height).toBe('large');
  });
});

describe('ItemEditForm — width defaults and RowComponent guard', () => {
  test('an item with no width defaults to 1, and mode switches preserve that default', () => {
    const onChange = jest.fn();
    renderItem({ onChange, item: { chart: '', table: '', markdown: '', selector: '', input: '' } });
    expect(screen.getByLabelText('Item 1 width')).toHaveValue(1);

    fireEvent.click(screen.getByTestId('item-row-0-item-0-mode-container'));
    expect(onChange.mock.calls[0][0].width).toBe(1);

    cleanup();
    onChange.mockClear();
    // Container without an explicit width switches back to a width-1 leaf.
    renderItem({ onChange, item: { rows: [] } });
    fireEvent.click(screen.getByTestId('item-row-0-item-0-mode-leaf'));
    expect(onChange.mock.calls[0][0].width).toBe(1);
  });

  test('a container renders safely without an injected RowComponent and can still add rows', () => {
    const onChange = jest.fn();
    render(
      <DndContext>
        <ItemEditForm
          item={containerItem}
          itemId="row-0-item-0"
          itemIndex={0}
          onChange={onChange}
          onSelectRef={() => {}}
        />
      </DndContext>
    );
    // No nested RowEditForms are rendered without the injected component…
    expect(screen.queryByTestId('row-edit-form-row-0-item-0-0')).not.toBeInTheDocument();
    // …but the container chrome still works.
    fireEvent.click(screen.getByText('+ Add Nested Row'));
    expect(onChange.mock.calls[0][0].rows).toHaveLength(3);
  });
});

describe('ItemEditForm — render-safe with no DndContext ancestor', () => {
  test('mounts without throwing (RefDropZone inert until G-1 shell DndContext)', () => {
    expect(() =>
      render(
        <ItemEditForm
          item={leafItem}
          itemId="solo-0"
          itemIndex={0}
          onChange={() => {}}
          RowComponent={RowEditForm}
        />
      )
    ).not.toThrow();
    expect(screen.getByText('rev_chart')).toBeInTheDocument();
  });
});

describe('ItemEditForm — right-rail "Choose…" click-to-pick (W5)', () => {
  let events;

  beforeEach(() => {
    events = [];
    setWorkspaceTelemetryListener(e => events.push(e));
    useStore.setState({
      charts: [{ name: 'revenue_chart' }],
      tables: [],
      markdowns: [],
      inputs: [],
      insights: [{ name: 'rev-insight' }],
      saveChart: jest.fn().mockResolvedValue({ success: true }),
      openCreateChartModal: jest.fn(),
      // VIS-1025: null = local serve (always editable). Set explicitly so a
      // read-only case can't leak into the neighbouring tests.
      capabilities: null,
    });
  });

  afterEach(() => {
    setWorkspaceTelemetryListener(null);
  });

  const openPicker = () => {
    fireEvent.click(screen.getByTestId('item-row-0-item-0-choose'));
    return screen.getByTestId('reference-picker');
  };

  test('an EMPTY leaf renders the Choose… affordance; a filled leaf does not', () => {
    renderItem({ item: emptyItem });
    expect(screen.getByTestId('item-row-0-item-0-choose')).toBeInTheDocument();

    cleanup();
    renderItem({ item: leafItem });
    expect(screen.queryByTestId('item-row-0-item-0-choose')).not.toBeInTheDocument();
  });

  test('Choose… opens the ReferencePicker listing charts AND insights', () => {
    renderItem({ item: emptyItem });
    expect(screen.queryByTestId('reference-picker')).not.toBeInTheDocument();
    openPicker();
    expect(screen.getByTestId('reference-picker-title')).toHaveTextContent(
      'Pick a chart or insight'
    );
    expect(screen.getByTestId('reference-picker-row-revenue_chart')).toBeInTheDocument();
    expect(screen.getByTestId('reference-picker-row-rev-insight')).toBeInTheDocument();
  });

  test('picking a CHART reports the item with the chart leaf set (working copy, #617)', () => {
    const onChange = jest.fn();
    renderItem({ item: emptyItem, onChange });
    openPicker();
    fireEvent.click(screen.getByTestId('reference-picker-row-revenue_chart'));

    // Born-valid item: exactly one leaf key, serialized ${ref()} form.
    expect(onChange).toHaveBeenCalledWith({ width: 1, chart: '${ref(revenue_chart)}' });
    expect(useStore.getState().saveChart).not.toHaveBeenCalled();
    expect(screen.queryByTestId('reference-picker')).not.toBeInTheDocument();

    const evt = events.find(e => e.eventName === 'canvas_action');
    expect(evt.payload).toMatchObject({
      kind: 'add_item',
      source: 'picker',
      type: 'chart',
      name: 'revenue_chart',
    });
    expect(evt.payload.wrapped_chart).toBeUndefined();
  });

  test('picking an INSIGHT auto-wraps: saves <insight>-chart and points the item at it (#637)', () => {
    const onChange = jest.fn();
    renderItem({ item: emptyItem, onChange });
    openPicker();
    fireEvent.click(screen.getByTestId('reference-picker-row-rev-insight'));

    expect(useStore.getState().saveChart).toHaveBeenCalledWith('rev-insight-chart', {
      insights: ['ref(rev-insight)'],
    });
    expect(onChange).toHaveBeenCalledWith({ width: 1, chart: '${ref(rev-insight-chart)}' });

    const evt = events.find(e => e.eventName === 'canvas_action');
    expect(evt.payload).toMatchObject({
      kind: 'add_item',
      source: 'picker',
      type: 'insight',
      name: 'rev-insight',
      wrapped_chart: 'rev-insight-chart',
    });
  });

  test('the minted wrapper name disambiguates with -2 against existing charts', () => {
    useStore.setState({ charts: [{ name: 'revenue_chart' }, { name: 'rev-insight-chart' }] });
    const onChange = jest.fn();
    renderItem({ item: emptyItem, onChange });
    openPicker();
    fireEvent.click(screen.getByTestId('reference-picker-row-rev-insight'));

    expect(useStore.getState().saveChart).toHaveBeenCalledWith('rev-insight-chart-2', {
      insights: ['ref(rev-insight)'],
    });
    expect(onChange).toHaveBeenCalledWith({ width: 1, chart: '${ref(rev-insight-chart-2)}' });
  });

  test('closing the picker changes nothing and mints nothing', () => {
    const onChange = jest.fn();
    renderItem({ item: emptyItem, onChange });
    openPicker();
    fireEvent.click(screen.getByTestId('reference-picker-close'));
    expect(screen.queryByTestId('reference-picker')).not.toBeInTheDocument();
    expect(onChange).not.toHaveBeenCalled();
    expect(useStore.getState().saveChart).not.toHaveBeenCalled();
  });

  // ── #637: a REJECTED placement must mint NOTHING ──────────────────────────
  // `setItemLeaf` normalises the picked name (it trims it, and drops a name
  // that trims to nothing), so the slot does not always end up referencing the
  // name the handler holds. Wherever it doesn't, saving a wrapper chart under
  // that name would leave an orphan draft chart pointed at by nothing — the
  // exact failure the #637 ordering exists to prevent.
  test('an insight whose wrapper name the transform rewrites mints NOTHING', () => {
    // `' rev'` → wrapper name `' rev-chart'`, which `setItemLeaf` TRIMS to
    // `rev-chart`: the slot would reference a DIFFERENT chart than the one
    // saveChart creates — an orphan draft plus a broken ref.
    useStore.setState({ insights: [{ name: ' rev' }] });
    const onChange = jest.fn();
    renderItem({ item: emptyItem, onChange });
    openPicker();
    fireEvent.click(screen.getByRole('button', { name: 'rev' }));

    expect(useStore.getState().saveChart).not.toHaveBeenCalled();
    expect(onChange).not.toHaveBeenCalled();
    expect(events.filter(e => e.eventName === 'canvas_action')).toHaveLength(0);
  });

  test('a chart whose name the transform drops places NOTHING', () => {
    useStore.setState({ charts: [{ name: ' orphan' }], insights: [] });
    const onChange = jest.fn();
    renderItem({ item: emptyItem, onChange });
    openPicker();
    fireEvent.click(screen.getByRole('button', { name: 'orphan' }));

    expect(onChange).not.toHaveBeenCalled();
    expect(events.filter(e => e.eventName === 'canvas_action')).toHaveLength(0);
  });

  // ── VIS-1025: read-only holds the ONE write that bypasses persistConfig ────
  // `saveChart` is fired straight at the store, so the rail's persistConfig
  // read-only hold cannot cover it: without this gate a read-only stage POSTs
  // a wrapper chart and THEN discards the placement — an orphan draft chart on
  // a project the user is not allowed to edit.
  describe('read-only stage (capabilities.can_edit === false)', () => {
    beforeEach(() => {
      useStore.setState({ capabilities: { can_edit: false, edit_action: 'Create a draft to edit' } });
    });

    test('the Choose… trigger is disabled and cannot open the picker', () => {
      renderItem({ item: emptyItem });
      const choose = screen.getByTestId('item-row-0-item-0-choose');
      expect(choose).toBeDisabled();
      fireEvent.click(choose);
      expect(screen.queryByTestId('reference-picker')).not.toBeInTheDocument();
      expect(useStore.getState().saveChart).not.toHaveBeenCalled();
    });

    test('a stage that flips read-only while the picker is OPEN holds the pick', () => {
      useStore.setState({ capabilities: null });
      const onChange = jest.fn();
      renderItem({ item: emptyItem, onChange });
      openPicker();

      // Capabilities flip mid-flow (e.g. the draft was published from another
      // tab). The mounted picker's rows are still live.
      act(() => {
        useStore.setState({ capabilities: { can_edit: false } });
      });
      fireEvent.click(screen.getByTestId('reference-picker-row-rev-insight'));

      expect(useStore.getState().saveChart).not.toHaveBeenCalled();
      expect(onChange).not.toHaveBeenCalled();
      expect(events.filter(e => e.eventName === 'canvas_action')).toHaveLength(0);
    });
  });

  // ── The rail and the canvas mount the SAME picker ─────────────────────────
  // ProjectCanvas passes `onCreateNew`; without it the picker's own empty
  // state renders "Create a chart to fill this slot" with nothing to click,
  // so an empty project's Choose… is a dead-end modal.
  test('an EMPTY project offers create-new from the picker (parity with the canvas)', () => {
    useStore.setState({ charts: [], insights: [] });
    renderItem({ item: emptyItem });
    openPicker();

    expect(screen.getByTestId('reference-picker-empty')).toBeInTheDocument();
    fireEvent.click(screen.getByTestId('reference-picker-empty-create'));

    expect(useStore.getState().openCreateChartModal).toHaveBeenCalledTimes(1);
    expect(screen.queryByTestId('reference-picker')).not.toBeInTheDocument();
    expect(events.find(e => e.eventName === 'inline_create_used').payload).toEqual({
      source: 'picker',
      kind: 'chart',
    });
  });

  test('the picker footer create link is available whenever objects exist', () => {
    renderItem({ item: emptyItem });
    openPicker();
    fireEvent.click(screen.getByTestId('reference-picker-create'));
    expect(useStore.getState().openCreateChartModal).toHaveBeenCalledTimes(1);
  });
});
