import React, { useState } from 'react';
import RefDropZone from './RefDropZone';
import ReferencePicker from '../project/canvas/ReferencePicker';
import useStore from '../../../stores/store';
import { emitWorkspaceEvent } from '../workspace/telemetry';
import { isReadOnly } from '../../../stores/branchingStore';
import { mintWrapperChartName, buildWrapperChartConfig } from '../../../utils/insightWrap';
import { parseRefValue } from '../../../utils/refString';
import {
  LEAF_REF_FIELDS,
  applyLeafRef,
  appendEmptyItem,
  convertItemToContainer,
  convertItemToLeaf,
  createRow,
  setItemWidth,
} from '../workspace/itemMutations';

export const ALLOWED_LEAF_TYPES = [...LEAF_REF_FIELDS];

/**
 * Resolve the `{ type, name }` leaf reference currently held by an item,
 * inspecting the per-type ref fields the dashboard model uses
 * (`chart` / `table` / `markdown` / `input`). Returns null when the item holds
 * no leaf ref (empty leaf, or a row-container).
 *
 * A leaf may be stored three ways and ALL must resolve:
 *   - a ref STRING  — `ref(name)` / `${ref(name)}` / a bare name (authoring), or
 *   - a NAMED compiled OBJECT — `{ name, path, insights, … }` (a real, named
 *     chart/table/etc. as it lands in project.json — VIS-802 GAP-1), or
 *   - an INLINE/unnamed OBJECT — markdown/etc. defined in place, with NO `name`.
 *     Its only identifier is an autogenerated `path`
 *     (`project.dashboards[0].rows[0].items[0].markdown`), which is NOT a usable
 *     object name. We surface these as `{ inline: true, name: null }` so the UI
 *     can render a "defined inline" chip instead of the raw path, and a pill
 *     click does not try to open a (nonexistent) object in the store/lineage.
 *
 * Returns `{ type, name, inline }` (name is null for inline leaves), or null
 * when the item holds no leaf ref.
 */
export const getItemLeafRef = item => {
  if (!item) return null;
  for (const field of LEAF_REF_FIELDS) {
    const val = item[field];
    if (!val) continue;
    if (typeof val === 'object') {
      if (val.name) return { type: field, name: val.name, inline: false };
      // Object with no name → inline/unnamed (its `path` is autogenerated).
      return { type: field, name: null, inline: true };
    }
    const name = parseRefValue(val);
    if (name) return { type: field, name, inline: false };
  }
  return null;
};

/** True when the item is acting as a row-container (`Item.rows` is set). */
export const isContainerItem = item => Array.isArray(item?.rows);

/**
 * Place `name` into the item's `type` leaf and PROVE the slot now points at
 * exactly that name.
 *
 * The truthiness check this replaced (`!next[type]`) could not fail for any
 * name the picker emits, so the "#637 rejected placement → mint nothing"
 * ordering had no teeth on this path. `setItemLeaf` NORMALISES the name — it
 * trims it, and drops it entirely when the trim leaves nothing — so what the
 * slot ends up referencing is not always the name the caller holds. Reading
 * the placed ref back is the postcondition that actually enforces the
 * invariant: the insight branch must never `saveChart` under a name the slot
 * does not point at, which is precisely an orphan draft chart plus a broken
 * ref in the slot.
 *
 * @returns the next item when the slot references `name` exactly, else null.
 */
const placeLeafRef = (item, type, name) => {
  const next = applyLeafRef(item, { type, name });
  if (!next || parseRefValue(next[type]) !== name) return null;
  return next;
};

/**
 * ItemEditForm — VIS-787 / Track F F-2.
 *
 * Standalone, presentational editor for a single dashboard item. Extracted out
 * of the previously-bundled item sub-section of <RowEditForm> /
 * <DashboardEditForm> so the same component drives both the bundled form (one
 * <ItemEditForm> per item, mounted by <RowEditForm>) and a future right-rail
 * standalone mount. All item state lives in the parent; this component is
 * controlled via a single `onChange(nextItem)` callback that reports the fully
 * updated item.
 *
 * Two variants, mutually exclusive (mirrors the Pydantic
 * `validate_unique_item_types` rule — at most one of chart/table/markdown/input
 * /rows may be set):
 *   - leaf      → one <RefDropZone> (`item-<itemId>-leaf`) accepting chart /
 *                 table / markdown / input. A filled slot shows an
 *                 <EmbeddedPill>; removing the pill clears the ref; clicking it
 *                 selects the referenced object via `onSelectRef`. Dropping a
 *                 second-type ref clears the existing leaf first (mutual
 *                 exclusion).
 *   - container → `Item.rows` is set: add / remove / reorder nested sub-rows,
 *                 each rendered with the (lazily-injected) RowEditForm.
 *
 * Props:
 *   - item        (object)  — the item config ({ width, chart, table, ..., rows }).
 *   - itemId      (string|number) — stable id used for the leaf drop-zone id and
 *                                   React keys (the item index today).
 *   - itemIndex   (number)  — 0-based; drives the "Item N" label.
 *   - onChange    (fn(nextItem)) — report the fully updated item.
 *   - onRemove    (fn)      — remove this item from its parent row.
 *   - onSelectRef (fn({ type, name })) — pill click → workspace selection.
 *   - RowComponent (component) — the RowEditForm to render nested sub-rows with.
 *                                Injected to avoid a static import cycle
 *                                (RowEditForm imports ItemEditForm).
 *   - leafDropZoneId (string) — (optional) override for the leaf <RefDropZone>
 *                                id. Defaults to `item-<itemId>-leaf`. The
 *                                bundled <RowEditForm> passes the legacy
 *                                `row-<rowId>-item-<idx>` id so existing
 *                                bundled behavior stays byte-identical.
 */
/**
 * LeafChooseControl — the W5 click-to-pick affordance for an EMPTY leaf slot:
 * a "Choose…" button that opens the same <ReferencePicker> the canvas
 * empty-slot click uses (charts + insights), so drag-and-drop is never the
 * only way to fill a slot from the right rail.
 *
 * A separate component (mounted only for empty leaves) so <ItemEditForm>
 * itself stays hook-free — its picker state lives here.
 *
 * A pick lands the SAME way a canvas pick does. A chart pick sets the item's
 * `chart` leaf. An insight pick AUTO-WRAPS (#637 pattern): mint the unique
 * `<insight>-chart` name (pure), validate the placement transform FIRST, and
 * only then save the wrapper chart — a rejected placement must never leave an
 * orphan draft chart. The item change flows through `onChange` into the
 * dashboard working copy (#617 — the explicit Save footer persists it).
 *
 * READ-ONLY (VIS-1025): `saveChart` is the ONE external side effect this form
 * fires outside `onChange`, so it is the one write the rail's `persistConfig`
 * hold cannot cover — on a read-only stage `persistConfig` discards the
 * placement AFTER the wrapper chart has already been POSTed, which is exactly
 * the orphan draft chart #637 forbids. The affordance is therefore disabled
 * (and the select handler held) whenever the stage is read-only.
 */
const LeafChooseControl = ({ item, itemId, onChange }) => {
  const [pickerOpen, setPickerOpen] = useState(false);
  const readOnly = useStore(isReadOnly);

  const handlePickerSelect = (pickedName, pickedType) => {
    setPickerOpen(false);
    if (!pickedName || !pickedType) return;
    // Belt-and-braces for a stage that flips read-only while the picker is
    // open: the trigger disables on the next render, but the mounted picker's
    // rows are still live, and a pick here would mint against a held write.
    if (readOnly) return;

    if (pickedType === 'insight') {
      const state = useStore.getState();
      const existingCharts = (state.charts || []).map(chart => chart.name);
      const chartName = mintWrapperChartName(pickedName, existingCharts);
      const next = placeLeafRef(item, 'chart', chartName);
      if (!next) return; // rejected placement → mint nothing
      if (typeof state.saveChart === 'function') {
        state.saveChart(chartName, buildWrapperChartConfig(pickedName));
      }
      onChange(next);
      emitWorkspaceEvent('canvas_action', {
        kind: 'add_item',
        source: 'picker',
        type: 'insight',
        name: pickedName,
        wrapped_chart: chartName,
        itemId,
      });
      return;
    }

    const next = placeLeafRef(item, pickedType, pickedName);
    if (!next) return;
    onChange(next);
    emitWorkspaceEvent('canvas_action', {
      kind: 'add_item',
      source: 'picker',
      type: pickedType,
      name: pickedName,
      itemId,
    });
  };

  // Create-new from the picker's empty state / footer. Without it a project
  // with no charts AND no insights opens a dead-end modal whose own copy
  // ("Create a chart to fill this slot") promises an action it cannot perform
  // — the canvas path passes one, so the two "same picker" surfaces must too.
  const handleCreateNew = typeKey => {
    setPickerOpen(false);
    if (readOnly) return;
    emitWorkspaceEvent('inline_create_used', { source: 'picker', kind: typeKey });
    const openCreateChartModal = useStore.getState().openCreateChartModal;
    if (typeKey === 'chart' && typeof openCreateChartModal === 'function') {
      openCreateChartModal();
    }
  };

  return (
    <>
      <button
        type="button"
        data-testid={`item-${itemId}-choose`}
        onClick={() => setPickerOpen(true)}
        disabled={readOnly}
        title={readOnly ? 'Read-only — create a draft to edit' : undefined}
        className="inline-flex items-center gap-1 text-xs font-medium text-primary-600 transition-colors hover:text-primary-700 disabled:cursor-not-allowed disabled:text-gray-400 disabled:hover:text-gray-400"
      >
        Choose…
      </button>
      {pickerOpen && (
        <ReferencePicker
          types={['chart', 'insight']}
          onSelect={handlePickerSelect}
          onClose={() => setPickerOpen(false)}
          onCreateNew={handleCreateNew}
        />
      )}
    </>
  );
};

const ItemEditForm = ({
  item,
  itemId,
  itemIndex,
  onChange,
  onRemove,
  onSelectRef,
  RowComponent,
  leafDropZoneId,
}) => {
  const isContainer = isContainerItem(item);
  const leafRef = getItemLeafRef(item);
  const resolvedLeafDropZoneId = leafDropZoneId || `item-${itemId}-leaf`;

  // Every structural mutation flows through itemMutations (VIS-993 §3) so the
  // emitted item is BORN backend-valid: integer widths, at most one leaf key
  // (mutual exclusion), never empty-string leaves or the non-model `selector`.
  const handleWidthChange = width => {
    onChange(setItemWidth(item, width));
  };

  /**
   * Set or clear the leaf ref. `ref` is `{ type, name }` to set, or `null` to
   * clear. itemMutations enforces the mutual exclusion: dropping a second-type
   * ref clears the existing leaf (and any container rows) before writing the
   * new one, so only one type is ever populated.
   */
  const handleLeafRefChange = ref => {
    onChange(applyLeafRef(item, ref));
  };

  const switchToContainer = () => {
    onChange(convertItemToContainer(item));
  };

  const switchToLeaf = () => {
    onChange(convertItemToLeaf(item));
  };

  const rows = item?.rows || [];

  const updateRow = (rowIndex, nextRow) => {
    onChange({ ...item, rows: rows.map((r, i) => (i === rowIndex ? nextRow : r)) });
  };

  const addRow = () => {
    onChange({ ...item, rows: [...rows, createRow()] });
  };

  const removeRow = rowIndex => {
    onChange({ ...item, rows: rows.filter((_, i) => i !== rowIndex) });
  };

  const moveRow = (rowIndex, delta) => {
    const target = rowIndex + delta;
    if (target < 0 || target >= rows.length) return;
    const next = [...rows];
    const [moved] = next.splice(rowIndex, 1);
    next.splice(target, 0, moved);
    onChange({ ...item, rows: next });
  };

  return (
    <div
      className="p-2 bg-white border border-gray-200 rounded space-y-2"
      data-testid={`item-edit-form-${itemId}`}
    >
      <div className="flex items-center justify-between">
        <span className="text-xs text-gray-500">Item {itemIndex + 1}</span>
        {onRemove && (
          <button
            type="button"
            onClick={onRemove}
            className="p-0.5 text-red-400 hover:text-red-600 rounded"
            aria-label={`Remove item ${itemIndex + 1}`}
          >
            <span style={{ fontSize: 14, lineHeight: 1 }}>&minus;</span>
          </button>
        )}
      </div>

      <div className="flex items-center gap-2">
        <label className="text-xs text-gray-500">Width:</label>
        <input
          type="number"
          min="1"
          value={item?.width ?? 1}
          onChange={e => handleWidthChange(e.target.value)}
          className="w-14 text-xs border border-gray-300 rounded px-1 py-0.5 focus:outline-none focus:ring-1 focus:ring-primary-500"
          aria-label={`Item ${itemIndex + 1} width`}
        />
      </div>

      {/* Leaf-vs-container choice */}
      <div className="flex items-center gap-2" role="radiogroup" aria-label={`Item ${itemIndex + 1} content type`}>
        <button
          type="button"
          role="radio"
          aria-checked={!isContainer}
          onClick={switchToLeaf}
          data-testid={`item-${itemId}-mode-leaf`}
          className={[
            'px-2 py-0.5 text-xs rounded border transition-colors',
            !isContainer
              ? 'bg-primary text-white border-primary'
              : 'bg-white text-gray-600 border-gray-300 hover:bg-gray-50',
          ].join(' ')}
        >
          Object
        </button>
        <button
          type="button"
          role="radio"
          aria-checked={isContainer}
          onClick={switchToContainer}
          data-testid={`item-${itemId}-mode-container`}
          className={[
            'px-2 py-0.5 text-xs rounded border transition-colors',
            isContainer
              ? 'bg-primary text-white border-primary'
              : 'bg-white text-gray-600 border-gray-300 hover:bg-gray-50',
          ].join(' ')}
        >
          Nested rows
        </button>
      </div>

      {isContainer ? (
        <div className="space-y-2 pl-2 border-l-2 border-gray-300" data-testid={`item-${itemId}-rows`}>
          {rows.map((row, rowIndex) => (
            <div key={rowIndex} className="space-y-1">
              <div className="flex items-center justify-end gap-1">
                <button
                  type="button"
                  onClick={() => moveRow(rowIndex, -1)}
                  disabled={rowIndex === 0}
                  className="px-1 text-xs text-gray-500 hover:text-gray-700 disabled:opacity-30"
                  aria-label={`Move nested row ${rowIndex + 1} up`}
                >
                  &uarr;
                </button>
                <button
                  type="button"
                  onClick={() => moveRow(rowIndex, 1)}
                  disabled={rowIndex === rows.length - 1}
                  className="px-1 text-xs text-gray-500 hover:text-gray-700 disabled:opacity-30"
                  aria-label={`Move nested row ${rowIndex + 1} down`}
                >
                  &darr;
                </button>
              </div>
              {RowComponent ? (
                <RowComponent
                  row={row}
                  rowId={`${itemId}-${rowIndex}`}
                  rowIndex={rowIndex}
                  onRemoveRow={() => removeRow(rowIndex)}
                  onHeightChange={height => updateRow(rowIndex, { ...row, height })}
                  onAddItem={() => updateRow(rowIndex, appendEmptyItem(row))}
                  onRemoveItem={subItemIndex =>
                    updateRow(rowIndex, {
                      ...row,
                      items: (row.items || []).filter((_, i) => i !== subItemIndex),
                    })
                  }
                  onItemWidthChange={(subItemIndex, width) =>
                    updateRow(rowIndex, {
                      ...row,
                      items: (row.items || []).map((it, i) =>
                        i === subItemIndex ? setItemWidth(it, width) : it
                      ),
                    })
                  }
                  onItemRefChange={(subItemIndex, ref) =>
                    updateRow(rowIndex, {
                      ...row,
                      items: (row.items || []).map((it, i) =>
                        i === subItemIndex ? applyLeafRef(it, ref) : it
                      ),
                    })
                  }
                  onSelectRef={onSelectRef}
                />
              ) : null}
            </div>
          ))}
          <button
            type="button"
            onClick={addRow}
            className="flex items-center gap-1 px-2 py-0.5 text-xs text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded transition-colors"
          >
            + Add Nested Row
          </button>
        </div>
      ) : (
        <div className="space-y-1.5">
          <RefDropZone
            id={resolvedLeafDropZoneId}
            allowedTypes={ALLOWED_LEAF_TYPES}
            value={leafRef}
            onClear={() => handleLeafRefChange(null)}
            onChange={ref => handleLeafRefChange(ref)}
            onSelectRef={onSelectRef}
            hint="Drop a chart, table, markdown, or input"
          />
          {/* W5 click-to-pick: click alternative to the drop zone, empty leaf
              only (a filled slot shows its pill; clear it first to re-pick). */}
          {!leafRef && <LeafChooseControl item={item} itemId={itemId} onChange={onChange} />}
        </div>
      )}
    </div>
  );
};

export default ItemEditForm;
