import React from 'react';
import { useDroppable } from '@dnd-kit/core';
import EmbeddedPill from '../lineage/EmbeddedPill';
import { parseRefValue } from '../../../utils/refString';

/**
 * RefDropZone — VIS-783 / Track F F-1.
 *
 * A thin wrapper around dnd-kit's `useDroppable` that represents a single
 * "object reference" slot (e.g. a dashboard item that points at one chart /
 * table / markdown / input). It is the shared primitive every ref slot in the
 * Dashboard-Building surfaces reuses; RowEditForm is its first consumer.
 *
 * Two visual states:
 *   - filled  → renders an <EmbeddedPill> for the referenced object. Clicking
 *               the pill calls `onSelectRef` (workspace selection); the pill's
 *               x calls `onClear`.
 *   - empty   → renders a dashed drop-zone with hint text.
 *
 * Drag-over feedback (only while a drag is in progress AND this zone is the
 * drop target):
 *   - valid type    → mulberry ring.
 *   - invalid type  → red flash + visually communicates rejection.
 *
 * IMPORTANT (G-1 coupling): `useDroppable` requires a `DndContext` ancestor to
 * actually receive drops. The shell-level shared DndContext is Track G G-1's
 * job and does NOT exist yet, so:
 *   - With no ancestor DndContext, `useDroppable` is inert (`isOver` stays
 *     false, `active` stays null) — RefDropZone still renders fine, no throw.
 *   - The drop write itself is performed by the shell's DndContext `onDragEnd`
 *     (G-1) which reads this zone's `data` ({ kind, allowedTypes, refId }) and
 *     calls back into the consumer. Until then, drops simply never fire.
 *
 * Props:
 *   - id           (string)   droppable id, e.g. `row-<rowId>-item-<idx>`.
 *   - allowedTypes (string[]) object types this slot accepts.
 *   - value        ({ type, name } | null) the current ref, or null/empty.
 *   - onChange     (fn)       (optional) — unused by the live drop path until
 *                             G-1 wires it; kept on the API so the shell /
 *                             tests can hand the zone a setter.
 *   - onClear      (fn)       called when the pill's x is clicked.
 *   - onSelectRef  (fn)       called with `{ type, name }` when the pill body
 *                             is clicked (workspace selection).
 *   - hint         (string)   (optional) empty-state hint text.
 */
const RefDropZone = ({
  id,
  allowedTypes = [],
  value = null,
  onChange,
  onClear,
  onSelectRef,
  hint = 'Drop an object here',
}) => {
  const { setNodeRef, isOver, active } = useDroppable({
    id,
    data: { kind: 'ref-slot', allowedTypes, refId: id, onChange },
  });

  // The active drag payload mirrors LibraryRow's `data.current`:
  // `{ source: 'library', type, name, subtype }`.
  const draggedType = active?.data?.current?.type ?? null;
  const isDragging = !!active;
  const isValidDrag = draggedType ? allowedTypes.includes(draggedType) : false;

  const showValid = isOver && isValidDrag;
  const showInvalid = isOver && isDragging && !isValidDrag;

  // Normalize value → { type, name, inline }. Accept either a structured object
  // or a bare/`${ref(name)}` string (callers may hand either).
  const refName = value
    ? typeof value === 'string'
      ? parseRefValue(value)
      : value.name
        ? parseRefValue(value.name)
        : null
    : null;
  const refType = value && typeof value === 'object' ? value.type : null;
  const isInline = !!(value && typeof value === 'object' && value.inline);

  const hasNamedRef = !!refName && !!refType;
  const hasInlineRef = isInline && !!refType;

  if (hasNamedRef) {
    return (
      <div ref={setNodeRef} data-testid={`ref-dropzone-${id}`} data-filled="true">
        <EmbeddedPill
          objectType={refType}
          label={refName}
          onClick={() => onSelectRef && onSelectRef({ type: refType, name: refName })}
          onRemove={onClear ? () => onClear() : undefined}
          tooltip={`${refType}: ${refName} — click to open`}
        />
      </div>
    );
  }

  // Inline (unnamed) leaf: render a muted "defined inline" chip rather than the
  // autogenerated path, and a hint prompting the user to name it. The chip is
  // NOT a link — clicking does not open lineage (an inline object isn't in the
  // store), it just keeps the item selected in this Edit panel.
  if (hasInlineRef) {
    return (
      <div ref={setNodeRef} data-testid={`ref-dropzone-${id}`} data-filled="inline">
        <EmbeddedPill
          as="div"
          objectType={refType}
          label="defined inline"
          onRemove={onClear ? () => onClear() : undefined}
          tooltip={`This ${refType} is defined inline (unnamed). Name it to edit it and include it in lineage.`}
        />
        <p className="mt-1 text-[11px] leading-snug text-gray-400">
          Name this {refType} to edit it and include it in lineage.
        </p>
      </div>
    );
  }

  const stateClasses = showInvalid
    ? 'border-red-400 bg-red-50 text-red-600 animate-pulse'
    : showValid
      ? 'border-[#713b57] ring-2 ring-[#713b57]/40 bg-[#f9f6f8] text-[#713b57]'
      : 'border-gray-300 text-gray-400 hover:border-gray-400';

  return (
    <div
      ref={setNodeRef}
      data-testid={`ref-dropzone-${id}`}
      data-filled="false"
      data-over={isOver ? 'true' : 'false'}
      data-valid-drag={showValid ? 'true' : 'false'}
      data-invalid-drag={showInvalid ? 'true' : 'false'}
      className={[
        'flex items-center justify-center rounded-md border border-dashed px-2 py-2 text-xs transition-all',
        stateClasses,
      ].join(' ')}
    >
      <span className="truncate">{showInvalid ? 'Type not allowed' : hint}</span>
    </div>
  );
};

export default RefDropZone;
