
version: 2

dashboards:
  - name: real_dash
    title: A real dashboard with fake data! 
    rows:
      - height: "40%"
      - height: "auto"
    columns:
      - width: "25%"
      - width: "50%"
      - width: "25%"
    items:
      - row: 1
        column: 1
        content: chart('waterfall_sales')
      - row: 1
        column: 2
        nested_grid:
          rows:
            - height: "50%"
            - height: "50%"
          columns:
            - width: "50%"
            - width: "50%"
          items:
            - row: 1
              column: 1
              content: chart('pam_product_breakout')
            - row: 2
              column: 2
              content: chart('pie_breakout')
      - row: 1
        column: 3
        content: chart('sales')

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
    meta: 
      using_ref: ref('my_first_dbt_model')
