"""Docs-vs-code parity guard (VIS-874).

The reference configuration docs are model-generated by
``mkdocs/src/write_mkdocs_markdown_files.py`` from the Pydantic schema, so they
*should* always reflect the code. This module is the GUARD that keeps that true
on every PR — it makes three classes of regression impossible to merge:

1. ``test_committed_schema_is_fresh`` — the committed
   ``visivo/src/visivo_project_schema.json`` must equal a freshly generated
   schema. Fails when someone edits a Pydantic model but forgets to run
   ``poetry run write-schema-json``. (This is the repo's standing rule; here CI
   enforces it.)

2. ``test_no_empty_reference_descriptions`` — every user-facing model that gets
   a generated reference page must have a non-empty class description in the
   schema (plus a conservative field-description check). This is the exact bug
   from VIS-968: docstrings placed *after* ``model_config`` (or attached to the
   wrong object) produced empty reference pages and were only caught by hand.

3. ``test_no_deprecated_terms_in_docs_prose`` — the hand-authored docs prose
   under ``mkdocs/`` must not contain 2.0-banned phrases (the YAML ``traces:``
   key, "trace types", "N+ trace types"). Mirrors the www linter at
   ``www/scripts/check-content-accuracy.cjs``.

The model list in checks 1 & 2 is derived the SAME way the doc generator derives
it (``Mkdocs.model_to_path_map``), so the guard can never drift out of sync with
what actually gets a page.
"""

import json
import re
from pathlib import Path

import pytest

from visivo.parsers.mkdocs import Mkdocs
from visivo.parsers.schema_generator import generate_schema
from visivo.utils import SCHEMA_FILE

# Repo root: tests/docs/test_docs_parity.py -> parents[2] == repo root.
REPO_ROOT = Path(__file__).resolve().parents[2]
MKDOCS_DIR = REPO_ROOT / "mkdocs"


# ---------------------------------------------------------------------------
# Shared schema / model-list fixtures (computed once — generating the schema is
# the expensive part).
# ---------------------------------------------------------------------------
@pytest.fixture(scope="module")
def mkdocs():
    return Mkdocs()


@pytest.fixture(scope="module")
def documented_models(mkdocs):
    """Exactly the models that get a generated reference page.

    Derived from ``Mkdocs.model_to_path_map`` — the same map the doc generator
    iterates in ``write_pydantic_md_files`` — so this list can never drift from
    what is actually written to ``mkdocs/reference/configuration/``.
    """
    return sorted(mkdocs.model_to_path_map.keys())


# ===========================================================================
# Check 1 — schema freshness
# ===========================================================================
def test_committed_schema_is_fresh():
    """The committed schema JSON must equal a freshly generated schema.

    If this fails, a Pydantic model changed without regenerating the schema.
    Fix by running ``poetry run write-schema-json`` and committing
    ``visivo/src/visivo_project_schema.json``.
    """
    committed = SCHEMA_FILE.read_text()
    fresh = generate_schema()

    # Compare parsed JSON first for a stable, key-order-independent diff, then
    # fall back to an exact-string assertion (``write-schema-json`` writes the
    # raw ``generate_schema()`` string, so the bytes should match too).
    assert json.loads(committed) == json.loads(fresh), (
        "Committed schema is stale. A Pydantic model changed but the schema was "
        "not regenerated. Run `poetry run write-schema-json` and commit "
        f"{SCHEMA_FILE}."
    )
    assert committed == fresh, (
        "Committed schema bytes differ from a freshly generated schema (the "
        "parsed JSON is equal, so this is a formatting drift). Run "
        f"`poetry run write-schema-json` and commit {SCHEMA_FILE}."
    )


# ===========================================================================
# Check 2 — no empty reference descriptions
# ===========================================================================
# Fields that legitimately carry no prose description because they are purely
# structural. We skip these by SHAPE where possible (const discriminators, and
# fields composed only of `oneOf`/`$ref`), and fall back to this explicit
# allowlist for the few remaining known-structural fields.
#
# `after_connect` is a connection-lifecycle hook (a list of SQL statements run
# after the source connects) shared by every SQL source; it currently ships
# without a description. If it ever gets a docstring, DELETE it from this set so
# the guard starts enforcing it.
STRUCTURAL_FIELD_ALLOWLIST = {"after_connect"}


def _is_structural_field(field_obj: dict) -> bool:
    """True for fields that need no prose description because their shape *is*
    the documentation (const discriminator values, or pure composition refs)."""
    # `const` discriminator (e.g. `type: "postgresql"`): the value documents it.
    if "const" in field_obj:
        return True
    # Composed-only fields (e.g. Insight.props -> oneOf, Insight.layout -> $ref).
    keys = set(field_obj.keys())
    if keys <= {"oneOf", "$ref", "title", "default"}:
        return True
    return False


def test_no_empty_reference_class_descriptions(mkdocs, documented_models):
    """Every model with a generated reference page must have a non-empty class
    description in the schema (the VIS-968 empty-page bug)."""
    defs = mkdocs.SCHEMA["$defs"]
    empty = []
    for model_name in documented_models:
        model_def = defs.get(model_name)
        assert model_def is not None, (
            f"Model {model_name!r} has a generated reference page "
            f"(in model_to_path_map) but no entry in the schema $defs."
        )
        description = model_def.get("description")
        if not description or not str(description).strip():
            empty.append(model_name)

    assert not empty, (
        "These models get a generated reference page but have an empty/whitespace "
        "class description, which produces a blank reference page (VIS-968). "
        "Add a class docstring (BEFORE `model_config`, attached to the class):\n  "
        + "\n  ".join(empty)
    )


def test_no_empty_reference_field_descriptions(mkdocs, documented_models):
    """Each documented field on a Pydantic-style reference model should have a
    non-empty description.

    Conservative: the prop/layout models render through a different (Plotly)
    code path, so they are excluded here; purely structural fields (const
    discriminators, composed `oneOf`/`$ref` fields, and the small
    ``STRUCTURAL_FIELD_ALLOWLIST``) are skipped so the guard flags only *prose*
    fields that silently lost their description.
    """
    defs = mkdocs.SCHEMA["$defs"]
    insight_prop_models = set(mkdocs._get_insight_prop_models())
    pydantic_models = [
        m for m in documented_models if m not in insight_prop_models and m.lower() != "layout"
    ]

    missing = []
    for model_name in pydantic_models:
        properties = defs.get(model_name, {}).get("properties", {})
        for field_name, field_obj in properties.items():
            if field_name in STRUCTURAL_FIELD_ALLOWLIST:
                continue
            if _is_structural_field(field_obj):
                continue
            description = field_obj.get("description")
            if not description or not str(description).strip():
                missing.append(f"{model_name}.{field_name}")

    assert not missing, (
        "These documented (non-structural) fields have an empty description, "
        "producing a blank Description cell in the reference table. Add a "
        "`Field(..., description=...)`:\n  " + "\n  ".join(missing)
    )


# ===========================================================================
# Check 3 — 2.0 deprecated-term scan over hand-authored docs prose
# ===========================================================================
# 2.0-banned phrases that must never appear in NEW docs prose. Keep this list in
# sync with the www linter (`www/scripts/check-content-accuracy.cjs`) and the
# "What Visivo IS / IS NOT" guardrails: traces were removed in 2.0 — charts come
# from Insights + the semantic layer.
#
# Deliberately CONSERVATIVE to avoid false positives:
#   - "stack trace" / "stacktrace" / "tracing" / "backtrace" are legitimate and
#     are NOT matched (the patterns target "trace" only as a YAML key or in the
#     phrase "trace types").
#   - The Plotly-generated prop docs (mkdocs/reference/props-docs/**) describe
#     Plotly "trace types" by name and are NOT our prose — they are excluded.
#   - The generated reference (mkdocs/reference/configuration/**, gitignored) is
#     excluded; check #2 guards its descriptions instead.
BANNED_DOC_TERMS = [
    # The 2.0 chart object is `insights:`, never the removed `traces:` key.
    ("traces: YAML key", re.compile(r"^\s*traces:", re.IGNORECASE)),
    # "N+ trace types" — a specific fabricated variant (clearer message).
    ("N+ trace types", re.compile(r"\b\d+\+?\s+trace types\b", re.IGNORECASE)),
    # Generic "trace types".
    ("trace types", re.compile(r"\btrace types\b", re.IGNORECASE)),
]

# Directories under mkdocs/ excluded from the prose scan:
#   - reference/configuration: model-generated, gitignored (check #2 guards it).
#   - reference/props-docs: Plotly-generated chart-type docs (legit "trace type"
#     usage describing Plotly itself), tracked but not authored by us.
EXCLUDED_DOC_SUBPATHS = (
    "reference/configuration/",
    "reference/props-docs/",
)


def _docs_prose_files():
    """All hand-authored mkdocs `.md` files, excluding generated/Plotly subtrees."""
    files = []
    for md in MKDOCS_DIR.rglob("*.md"):
        rel = md.relative_to(MKDOCS_DIR).as_posix()
        if any(rel.startswith(prefix) for prefix in EXCLUDED_DOC_SUBPATHS):
            continue
        files.append(md)
    return files


def test_docs_prose_files_are_discovered():
    """Sanity guard: the scan actually finds prose files (catches a bad glob or
    a moved docs tree that would silently make check #3 a no-op)."""
    files = _docs_prose_files()
    assert files, f"No hand-authored docs prose found under {MKDOCS_DIR}"


def test_no_deprecated_terms_in_docs_prose():
    """Scan hand-authored docs prose for 2.0-banned phrases."""
    violations = []
    for md in _docs_prose_files():
        rel = md.relative_to(REPO_ROOT).as_posix()
        for line_no, line in enumerate(md.read_text().splitlines(), start=1):
            for label, pattern in BANNED_DOC_TERMS:
                if pattern.search(line):
                    violations.append(f"{rel}:{line_no}: [{label}] {line.strip()}")

    assert not violations, (
        "2.0-banned phrase(s) found in hand-authored docs prose (traces were "
        "removed in 2.0 — use Insights + the semantic layer). Keep in sync with "
        "www/scripts/check-content-accuracy.cjs:\n  " + "\n  ".join(violations)
    )
