name: "visivo_qa"
version: "1.0.0"
config-version: 2

profile: "visivo_profile"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  visivo_qa:
    example:
      +materialized: view
      schema: example
    salesmart:
      +materialized: table
      schema: salesmart
