version: 2


sources:
  - name: crm
    description: PLEASE UPDATE SCHEMA DESCRIPTION
    database: raw
    schema: crm
  
    tables:
      - name: closed_deals
        description: Table with transaction level deal data after accounting records sales transactions.
        columns:
          - name: created_at
            description: PLEASE UPDATE DESCRIPTION

          - name: product
            description: PLEASE UPDATE DESCRIPTION

          - name: sales_rep
            description: PLEASE UPDATE DESCRIPTION

          - name: amount
            description: PLEASE UPDATE DESCRIPTION


      - name: sales_funnel_daily
        description: Daily snapshot of the number of deals in the sales database. 
        columns:
          - name: revenue_from_closes
            description: PLEASE UPDATE DESCRIPTION

          - name: mqls
            description: PLEASE UPDATE DESCRIPTION

          - name: closes
            description: PLEASE UPDATE DESCRIPTION

          - name: sals
            description: PLEASE UPDATE DESCRIPTION

          - name: as_of_date
            description: PLEASE UPDATE DESCRIPTION

          - name: demos
            description: PLEASE UPDATE DESCRIPTION

          - name: leads
            description: PLEASE UPDATE DESCRIPTION
