name: Deploy Viewer

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy-viewer:
    name: "Deploy Viewer"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
        
      - name: Build App
        run: cd viewer && yarn install && yarn deploy && cd ..

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Visivo
          author_email: info@visivo.io
          message: 'Build viewer for Python package'
      
      - name: Trigger Core Deployment
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.CORE_DEPLOY_TOKEN }}
          repository: visivo-io/core
          event-type: visivo-merge