name: Build & Deploy Docs Examples Site
on:
  push:
    branches:
      - main
  workflow_dispatch:
    
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      
      - name: Install visivo
        run: | 
          python -m pip install git+https://github.com/visivo-io/visivo.git@main
      
      - name: Install playwright
        run: |
          pip install playwright
          python -m playwright install webkit --with-deps

      - name: Install and Build
        run: |
          cd test-projects/docs-examples
          visivo compile
          visivo run -tm all
          visivo dist
          
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './test-projects/docs-examples/dist'
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NEW_NETLIFY_JARED_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_DOCS_EXAMPLES }}
