name: Build & Deploy Docs Examples Site
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install and Build
        run: |
          pip install visivo
          cd test-projects/docs-examples
          visivo dist
          cp _redirects dist
          
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './test-projects/docs-examples/dist'
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_JARED }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_DOCS_EXAMPLES }}
