name: Test Rails

on:
  pull_request:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-rails:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.3'
          bundler-cache: true
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - uses: Gr1N/setup-poetry@v8 

      - name: Install CLI Dependencies
        run: poetry install
      
      - name: Install CLI Visivo Package
        run: poetry build && pip install dist/visivo-*-py3-none-any.whl 
      
      - name: Install Dependencies
        run: cd test-projects/ror && bundle install && cd ../..
      
      - name: Test App
        run: cd test-projects/ror && bundle exec rspec && cd ../..
  